# This is a basic workflow to help you get started with Actions

name: PSEudamedTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Upgrade to latest powershell on Linux
        run: |
          # docs: https://learn.microsoft.com/de-de/powershell/scripting/install/install-other-linux?view=powershell-7.3#installation-using-a-binary-archive-file
          # Download the powershell '.tar.gz' archive
          curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/powershell-7.4.0-linux-x64.tar.gz
          # Create the target folder where powershell will be placed
          sudo mkdir -p /opt/microsoft/powershell/7
          # Expand powershell to the target folder
          sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
          # Set execute permissions
          sudo chmod +x /opt/microsoft/powershell/7/pwsh
          # not necessary:
          # Create the symbolic link that points to pwsh
          # sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh


      # Skript ausführen
      - name: PSEudamed.PS1 laden und Abfragen ausführen
        run: |
          . ./PSEudamed.PS1
          ./Tests/Abfragen.PS1
          ./Tests/Abfrage-Hersteller.PS1
          ./Tests/Abfrage-CNDs.PS1
          ./Tests/Abfrage-Zertifikate.PS1
        shell: pwsh
